### ISSUE TITLE
Binary files in dart6-data are installed without being decompressed

### ISSUE THREAD

**Issue by scpeters** [dartsim/dart-debian#3]
While testing an [ign-physics pull request](https://bitbucket.org/ignitionrobotics/ign-physics/pull-requests/2/created-operationalspacecontroller-plugin/activity#comment-49475083), I had trouble finding the example models in the [data folder](https://github.com/dartsim/dart/tree/master/data) in the debian packages. Since they are installed with a source build, I think they should be included in one of the debian packages.

cc @mxgrey

**Comment by jslee02** [comment]
Hm, that's weird. We have [`dart6-data`](https://github.com/dartsim/dart-debian/blob/release-6.3/trusty/debian/dart6-data.install) for installing the data folder and [it's included in `libdart6-all-dev`](https://github.com/dartsim/dart-debian/blob/release-6.3/trusty/debian/control#L700). :thinking:

**Comment by scpeters** [comment]
You are right! I didn't see it because I was grepping for `libdart`. Thanks

**Comment by scpeters** [comment]
It looks like a bunch of the files are gzipped though

**Comment by scpeters** [comment]
~~~
$ dpkg -L dart6-data | grep KR5
/usr/share/doc/dart/data/urdf/KR5
/usr/share/doc/dart/data/urdf/KR5/ground.urdf
/usr/share/doc/dart/data/urdf/KR5/KR5 sixx R650.urdf.gz
/usr/share/doc/dart/data/urdf/KR5/meshes
/usr/share/doc/dart/data/urdf/KR5/meshes/palm.STL.gz
/usr/share/doc/dart/data/urdf/KR5/meshes/shoulder.STL.gz
/usr/share/doc/dart/data/urdf/KR5/meshes/bicep.STL.gz
/usr/share/doc/dart/data/urdf/KR5/meshes/forearm.STL.gz
/usr/share/doc/dart/data/urdf/KR5/meshes/base_link.STL.gz
/usr/share/doc/dart/data/urdf/KR5/meshes/wrist.STL.gz
/usr/share/doc/dart/data/urdf/KR5/meshes/elbow.STL.gz
~~~

**Comment by jslee02** [comment]
> It looks like a bunch of the files are gzipped though

I believe those files are compressed as being packaged as debian package and will be extracted when they are installed. `dart6-data` just [copies](https://github.com/dartsim/dart-debian/blob/release-6.3/trusty/debian/dart6-data.install#L1) the raw data files under `<dart>/data`. For example, the KR5 files are at [here](https://github.com/dartsim/dart/tree/release-6.4/data/urdf/KR5/meshes) (unzipped).

**Comment by scpeters** [comment]
They still look compressed to me:

~~~
$ find /usr/share/doc/dart/data/urdf | grep KR5
/usr/share/doc/dart/data/urdf/KR5
/usr/share/doc/dart/data/urdf/KR5/KR5 sixx R650.urdf.gz
/usr/share/doc/dart/data/urdf/KR5/ground.urdf
/usr/share/doc/dart/data/urdf/KR5/meshes
/usr/share/doc/dart/data/urdf/KR5/meshes/wrist.STL.gz
/usr/share/doc/dart/data/urdf/KR5/meshes/base_link.STL.gz
/usr/share/doc/dart/data/urdf/KR5/meshes/bicep.STL.gz
/usr/share/doc/dart/data/urdf/KR5/meshes/forearm.STL.gz
/usr/share/doc/dart/data/urdf/KR5/meshes/palm.STL.gz
/usr/share/doc/dart/data/urdf/KR5/meshes/shoulder.STL.gz
/usr/share/doc/dart/data/urdf/KR5/meshes/elbow.STL.gz
~~~

**Comment by scpeters** [comment]
The STL and urdf files have `.gz` extensions in the `dart6-data` deb

**Comment by jslee02** [comment]
I could reproduce this issue. When I replied above, I was confused because the compressed and uncompressed files existed at the same time in the same directory. But that's because I installed uncompressed files manually a while ago, and `dart6-data` installed the compressed files.

Let me try to figure out what's the cause.

**Comment by jslee02** [comment]
[It seems overriding `dh_compress` should work](http://man.he.net/man1/dh_compress) as
```
# rules file
override_dh_compress:
	dh_compress --exclude=*/share/doc/data/dart/*
```

Let me try with this.

**Comment by scpeters** [comment]
Did you have a chance to try overriding `dh_compress`?

**Comment by jslee02** [comment]
Yes. I tried following script
```
override_dh_compress:
	dh_compress -X.STL
```
but it seemed not working (see [build log](https://launchpadlibrarian.net/349062357/buildlog_ubuntu-trusty-amd64.dart6_6.3.0.ppa3~trusty_BUILDING.txt.gz)). It didn't install any of data files weirdly. Let me investigate further.

**Comment by jslee02** [comment]
Oh, it actually worked. I only checked amd64 build but `dart6-data` is only built in i386. This is probably because `dart6-data` is non-binary package so it doesn't need to be built for both of architectures.

For a test, I just excluded `*.stl`, and this is what I get:
```
find /usr/share/doc/dart/data/urdf | grep stl
/usr/share/doc/dart/data/urdf/test/invalid_mesh.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_RAP_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_LSP_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_NK2.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_RWP_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_LHP_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_LSY_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_LF2.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_RKP_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_NK1_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_RSY_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_LF3.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_LWP_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_RAR_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_RF1.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_LWY_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_RWY_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_RHY_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_LAP_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_LAR_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_LEP_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_LF1.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_TSY_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_RF3.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_LKP_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_RHP_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_Torso_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_RWR_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_RF2.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_REP_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_LHY_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_LHR_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_RSR_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_LWR_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_NKY_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_LSR_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_RSP_merged.stl
/usr/share/doc/dart/data/urdf/drchubo/meshes/convhull_RHR_merged.stl
```

Other extensions are all excluded, and they are being built now. You should be able to check it in about a half hour.

**Comment by scpeters** [comment]
Thanks, it looks good now!
