### ISSUE TITLE
Update versions in changelog

### ISSUE THREAD

**Issue by scpeters** [dartsim/dart-debian#6]
There are some new debs built for version 6.8.0 but they are labeled as 6.7.2; I assume because the latest entry in the changelog files is 6.7.2.

* https://github.com/dartsim/dart-debian/blob/master/bionic/debian/changelog
* https://launchpad.net/~dartsim/+archive/ubuntu/ppa/+packages

We use the following script for updating changelog entries for our software, so you may find it useful:

* https://bitbucket.org/osrf/release-tools/src/b6ae2f2928c45458f30d365a632a870fa8050034/release-repo-scripts/changelog_spawn.sh?at=default&fileviewer=file-view-default

**Comment by jslee02** [comment]
The script is super useful, thanks! I modified it a bit for git and [pushed it](https://github.com/dartsim/dart-debian/commit/a43e9da7140ab86e02898ec399f023b71461bac9).
