### ISSUE TITLE
dart.pc pkgconfig file is not included in debian package

### ISSUE THREAD

**Issue by scpeters** [dartsim/dart-debian#7]
While looking at https://github.com/dartsim/dart/pull/1527, I was trying to figure out where the `dart.pc` file is installed in the debian binaries, but I think it is not included in any of the `.install` files. Am I missing something? I would expect it to be included in `libdart6-dev.install` along with the cmake config files.

**Comment by jslee02** [comment]
Good catch! This should be fixed by https://github.com/dartsim/dart-debian/commit/a4980775a1eacc2ea0a3308043ddfc69aaaa6f70. Let me close this issue once the builds on Launchpad is successfully done.

**Comment by jslee02** [comment]
Closing as confirmed that `dart.pc` is being correctly installed: [build log](https://launchpadlibrarian.net/514051592/buildlog_ubuntu-bionic-amd64.dart6_6.9.5-1885~202012282345~ubuntu18.04.1_BUILDING.txt.gz)
