### ISSUE TITLE
Fresh packages are not available for Ubuntu 22

### ISSUE THREAD

**Issue by ntfshard** [dartsim/dart-debian#9]
Hello

It feels like packages are has different version in title and inside package (in config.hpp: 6.13.2, package title 6.13.0) and newer versions are not available for downloading.

**Comment by ntfshard** [comment]
Friendly ping :)

**Comment by jslee02** [comment]
Hi @ntfshard, [the version info now correctly refers to 6.13.2 on Ubuntu 22](https://launchpad.net/~dartsim/+archive/ubuntu/ppa). As a next step, let me update it to the latest version (6.14.x).

**Comment by ntfshard** [comment]
Thank you for support!

**Comment by jslee02** [comment]
6.14.4 is now available on 22.04, 24.04, and 24.10. Closing this issue, but feel free to reopen if there are more unsolved issues.
